### PR TITLE
Concept introduction

### PR DESCRIPTION
**Pull request by koosvanamerongen**
Started writing down an intro section and removed the minibixel exposure
figure, which is irrelevant.

### CODE REVIEW

**Review by MatthewPeterKelly — CHANGES_REQUESTED** [review]
This looks great!  Two quick changes to remove build artifacts from version control:
- remove the file:  `root.synctex`
- add the line `**/*.synctex` to the file `latex/.gitignore

**Comment by koosvanamerongen** [comment]
Matthew, I've been looking into the history (quite handy) and found the pull request that contained my introduction concept. Seems like you've closed the request on 01/07 without merging it in. Not sure if that was on purpose. If not, could you restore the request and accept it. Otherwise, I'm curious why :)

**Comment by MatthewPeterKelly** [comment]
I think that I just made a mistake and closed it instead of merging. It is probably going to not be an easy thing to merge back in. My vote would be that you check out the dead branch, and then copy-paste you updates to the intro somewhere outside of git. Then checkout a new branch off of master and then copy-paste the edits back where they are supposed to go, careful not to delete any of the new changes. Then make a new pull request on the newer branch from master. There are lots of other ways to do this as well.

Sorry for the confusion!

**Comment by koosvanamerongen** [comment]
No problem. I recovered the old intro and have sent out a new pull request. Nothing changed to the intro in the meantime. The intro doesn't fit in perfectly anymore, but I'll leave it this way until David has restructured the doc.

**Comment by MatthewPeterKelly** [comment]
Great - thanks!

**Pull request closed without merging**
